name: ğŸ·ï¸ Add bugs to the Folksonomy GitHub Project

on:
  issues:
    types:
      - opened, labeled

jobs:
  add-to-project:
    name: ğŸ·ï¸ Add issue to the Folksonomy GitHub Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/5
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          label-operator: AND
