# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ * ]
  pull_request:
    branches: [ * ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # install Python
    Install Python 3.8+
    #Install pip
    pip install -r requirements.txt
    #Install postgre
    #Create a user
    # run PIP
    # Run generation
    ./generate_openapi_json.py
    # print json path

    # Runs a single command using the runners shell
    - name: swagger-cli
      uses: vaibhav-jain/spectral-action/@v2.6
      with:
        file_path: examples/swagger.yaml
